name: Integration

on:
  push:
    branches: 
      - main
    tags:
      - '*'
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: minafoundation-default-runners
  
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v3    

    - name: 📥 Update Git Submodules
      run: |
        git submodule init
        git submodule update

    - name: 📦 Install Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: 🤌 Get Minimina
      uses: MinaFoundation/install-minimina-action@v1
      with:
        stream: stable

    - name: Test Minimina
      run: |
        minimina network create
        minimina network start
        sleep 10
        minimina network status
        minimina network info
        minimina network stop
        minimina network delete

    # - name: 🛠️ Build Docker
    #   env:
    #     TAG: integtation-test
    #   run: nix-shell --run "make docker"

